---

name: manual-workflow

on:
    workflow_dispatch:
      

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: print context info
            run: |
                echo "${{ toJson(github) }}"
                echo "${{ toJson(vars) }}"
            if: github.ref == 'refs/heads/main'
                
          - name: get the code
            uses: actions/checkout@v6
          - name: Initialize CodeQL
            uses: github/codeql-action/init@v4
            with:
                languages: java
            if: github.ref != 'refs/heads/main'
          - name: package the code
            run: mvn --batch-mode  -Dmaven.test.failure.ignore=true test
          - name: Perform code quality analysis
            uses: github/codeql-action/analyze@v4
            if: github.ref != 'refs/heads/main'
          - name: publish test results
            uses: EnricoMi/publish-unit-test-result-action@v2
            with:
                files: "**/target/surefire-reports/**/*.xml"
                comment_mode: always