---

name: pull-request-workflow

on:
    pull_request:
        branches:
          - dev

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: get the code
            uses: actions/checkout@v6
          - name: package the code
            run: mvn --batch-mode  -Dmaven.test.failure.ignore=true test
          - name: publish test results
            uses: EnricoMi/publish-unit-test-result-action@v2
            with:
                files: "**/target/surefire-reports/**/*.xml"
                comment_mode: always